In [15]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 13 13:57:42 2020
@author: lihongyu
"""
#import the libraries
import numpy as np #basic math
import matplotlib.pyplot as plt #plot charts
import pandas as pd #

#import dataset
dataset = pd.read_csv('pid-5M.csv')

# A) unmodified data set
dfA = np.array(dataset)

# B) data set with all observations with zero values for inner or outer energy removed
b = False
if (b == True):
    global dfB
    dfB = dfA
    temp = dfB[:,5] != 0
    dfB = dfB[temp]
    temp = dfB[:,6] != 0
    dfB = dfB[temp]

# C) data set with outer and inner energy features removed
c = False
if (c == True):
    global dfC
    dfC = dfA[:,0:4]

# D) data set with zero values for outer and inner energy replaced with label averages for inner and outer energy

d = True
if (d == True):
    global dfD
    dfD = dfA
    labels = [211., 321., -11., 2212.]
    for label in labels:
        is_label = dfD == label
        label_features = dfD[is_label[:,0],5:7]
        label_averages = np.sum(label_features, axis=0)/label_features.shape[0]
        dfD[np.where(dfD[:,5]==0),5]=label_averages[0]
        dfD[np.where(dfD[:,6]==0),6]=label_averages[1]


X = dataset.iloc[:, 1:8].values # the features
y = dataset.iloc[:, 0].values # the dependent variable

# temp = dfA[:,0] != -11
# dfA = dfA[temp]
# temp = dfA[:,0] != 2212
# dfA = dfA[temp]
# temp = dfA[:,0] != 211
# dfA = dfA[temp]


X = dfD[:, 1:8] # the features
y = dfD[:, 0] # the dependent variable

#Splitting the dataset into Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


y_test_array = np.array(y_train)
y_test_number = np.unique(y_test_array)
print(y_test_number)
y_test_array = np.array(y_test)
y_test_number = np.unique(y_test_array)
print(y_test_number)

[[2.11000000e+02 7.80041000e-01 1.08148000e+00 ... 0.00000000e+00
  4.26001558e-02 5.22500829e-02]
 [2.11000000e+02 2.60929000e-01 7.78892000e-01 ... 0.00000000e+00
  4.26001558e-02 5.22500829e-02]
 [2.21200000e+03 7.73022000e-01 1.85953000e-01 ... 4.00000000e+00
  1.01900000e-01 5.22500829e-02]
 ...
 [2.11000000e+02 8.27497000e-01 6.89746000e-01 ... 0.00000000e+00
  4.26001558e-02 5.22500829e-02]
 [2.21200000e+03 1.33120000e+00 3.82746000e-01 ... 0.00000000e+00
  3.69421000e-02 5.69467000e-02]
 [2.21200000e+03 2.95689000e+00 4.49482000e-01 ... 0.00000000e+00
  1.06844000e-01 1.65438000e-01]]
[ -11.  211.  321. 2212.]
[ -11.  211.  321. 2212.]


In [22]:
#Logistic Regression
#Ftting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
lg_classifier = LogisticRegression(penalty='l2', solver='sag', multi_class='auto')
lg_classifier.fit(X_train, y_train)

#Predicting the Test set results
y_pred = lg_classifier.predict(X_test)

#In the prediction, there are only three classes, as we can see from the code below to print out the values in y_pred
y_test_array = np.array(y_pred)
y_test_number = np.unique(y_test_array)
print(y_test_number)


#Calculating accuracy for Logistic Regression
from sklearn.metrics import accuracy_score
print("Accuracy from Logistic Regression is: ")
print(accuracy_score(y_test, y_pred))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


[ -11.  211. 2212.]
Accuracy from Logistic Regression is: 
0.930912


In [20]:
#Navie Bayes
#Ftting Navie Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

#Predicting the Test set results
y_pred = nb_classifier.predict(X_test)

#In the prediction, there are only three classes, as we can see from the code below to print out the values in y_pred
y_test_array = np.array(y_pred)
y_test_number = np.unique(y_test_array)
print(y_test_number)


#Calculating accuracy for Navie Bayes
from sklearn.metrics import accuracy_score
print("Accuracy from Navie Bayes is: ")
print(accuracy_score(y_test, y_pred))

[ -11.  211.  321. 2212.]
Accuracy from Navie Bayes is: 
0.8513416


In [ ]:
#SVM
from sklearn.svm import LinearSVC
svm_classifier = LinearSVC()
svm_classifier.fit(X_train, y_train)

#Predicting the Test set results
y_pred = svm_classifier.predict(X_test)

#In the prediction, there are only three classes, as we can see from the code below to print out the values in y_pred
y_test_array = np.array(y_pred)
y_test_number = np.unique(y_test_array)
print(y_test_number)


#Calculating accuracy for SVM
from sklearn.metrics import accuracy_score
print("Accuracy from SVM is: ")
print(accuracy_score(y_test, y_pred))

In [ ]:
#Neural Network
#Ftting Neural Network to the Training set
from sklearn.neural_network import MLPClassifier
nn_classifier = MLPClassifier()
nn_classifier.fit(X_train, y_train)

#Predicting the Test set results
y_pred = nn_classifier.predict(X_test)

#In the prediction, there are only three classes, as we can see from the code below to print out the values in y_pred
y_test_array = np.array(y_pred)
y_test_number = np.unique(y_test_array)
print(y_test_number)


#Calculating accuracy for SVM
from sklearn.metrics import accuracy_score
print("Accuracy from Neural Network is: ")
print(accuracy_score(y_test, y_pred))